package com.financelog.service;

import com.financelog.core.DeploymentStage;
import software.amazon.awscdk.*;
import software.amazon.awscdk.services.cloudfront.*;
import software.amazon.awscdk.services.cloudfront.origins.S3BucketOrigin; // Note the new class
import software.amazon.awscdk.services.s3.*;
import software.amazon.awscdk.services.certificatemanager.Certificate;
import software.amazon.awscdk.services.ssm.StringParameter;
import software.constructs.Construct;
import com.financelog.core.ApplicationEnvironment;
import java.util.List;

/**
 * <h1>React Frontend Infrastructure</h1>
 *
 * <p>
 * This stack deploys a "Static Site" architecture designed for Single Page Applications (SPAs).
 * </p>
 *
 * * <h3>How it works (The React Lifecycle):</h3>
 *
 * <ul>
 * <li><b>Storage (S3):</b> Acts as a simple hard drive for the compiled JS/CSS/HTML files.</li>
 * <li><b>The Entry Point (index.html):</b> The only real file the browser loads. It contains
 * a {@code <div id="root">} where React "paints" the UI.</li>
 * <li><b>Routing Trick:</b> Since React handles navigation internally, refreshing a page like
 * {@code /dashboard} would normally cause an S3 404. We fix this by telling CloudFront
 * to redirect all errors back to {@code index.html}.</li>
 * </ul>
 */
public class FrontendStack extends Stack {

    private final Distribution distribution;

    private final Bucket frontendBucket;

    /**
     * Constructs the FrontendStack.
     * * @param scope Standard CDK construct scope.
     * @param constructId Unique identifier for the stack.
     * @param awsEnvironment Target AWS account and region (forced to us-east-1).
     * @param applicationEnvironment Custom wrapper providing naming conventions and tagging.
     * @param certificateArn The ARN of the SSL certificate for "app.finance-log.com".
     */
    public FrontendStack(
            final Construct scope,
            final String constructId,
            final Environment awsEnvironment,
            final ApplicationEnvironment applicationEnvironment,
            final String certificateArn
    ) {
        super(scope, constructId, StackProps.builder()
                .stackName(applicationEnvironment.prefix("frontend-stack"))
                .env(awsEnvironment)
                .build());

        /*
         * 1. S3 BUCKET: The "Filing Cabinet"
         * Stores the 'dist' or 'build' folder generated by your React build command.
         * We use BUCKET_OWNER_ENFORCED to work with modern Origin Access Control (OAC).
         */
        this.frontendBucket = Bucket.Builder.create(this, "FrontendBucket")
                .bucketName(applicationEnvironment.prefix("frontend-assets"))
                .blockPublicAccess(BlockPublicAccess.BLOCK_ALL)
                .encryption(BucketEncryption.S3_MANAGED)
                // OAC requires Object Ownership to be "Bucket Owner Enforced"
                .objectOwnership(ObjectOwnership.BUCKET_OWNER_ENFORCED)
                .removalPolicy(RemovalPolicy.DESTROY)
                .autoDeleteObjects(true)
                .build();

        /*
         * 2. CLOUDFRONT DISTRIBUTION: The "Delivery Engine"
         * This provides the HTTPS layer and the global CDN.
         */
        this.distribution = Distribution.Builder.create(this, "FrontendDistribution")
                .domainNames(List.of("app.finance-log.com"))
                // defaultRootObject ensures that visiting app.finance-log.com/ loads index.html
                .defaultRootObject("index.html")
                .certificate(Certificate.fromCertificateArn(this, "FrontendCertificate", certificateArn))
                .minimumProtocolVersion(SecurityPolicyProtocol.TLS_V1_2_2021)
                .defaultBehavior(BehaviorOptions.builder()
                        // OAC (Origin Access Control) is the secure "handshake" between CloudFront and S3
                        .origin(S3BucketOrigin.withOriginAccessControl(frontendBucket))
                        .viewerProtocolPolicy(ViewerProtocolPolicy.REDIRECT_TO_HTTPS)
                        .compress(true)
                        .cachePolicy(CachePolicy.CACHING_OPTIMIZED)
                        .build())
                /*
                 * THE SPA ROUTING FIX:
                 * If a user refreshes on 'app.com/settings', S3 will return a 404 because that file
                 * doesn't exist on disk. We intercept that 404, return index.html instead, and
                 * let React's internal router figure out that it needs to show the settings page.
                 */
                .errorResponses(List.of(
                        ErrorResponse.builder().httpStatus(403).responseHttpStatus(200).responsePagePath("/index.html").ttl(Duration.seconds(0)).build(),
                        ErrorResponse.builder().httpStatus(404).responseHttpStatus(200).responsePagePath("/index.html").ttl(Duration.seconds(0)).build()
                ))
                .build();

        // 3. STORAGE FOR CI/CD
        // We save these IDs in SSM so a GitHub Action or Jenkins can easily
        // find them to run 'aws s3 sync' or 'aws cloudfront create-invalidation'.
        putParameter(
                "CloudFrontDistributionIdParameter",
                applicationEnvironment.getDeploymentStage(),
                FrontendOutputs.PARAMETER_CLOUDFRONT_DISTRIBUTION_ID,
                distribution.getDistributionId()
        );
        putParameter(
                "CloudFrontDomainNameParameter",
                applicationEnvironment.getDeploymentStage(),
                FrontendOutputs.PARAMETER_CLOUDFRONT_DOMAIN_NAME,
                distribution.getDistributionDomainName()
        );

        // Standard CDK Outputs for terminal visibility
        new CfnOutput(this, "CloudFrontDomainName", CfnOutputProps.builder()
                .exportName(applicationEnvironment.prefix("frontend-cloudfront-domain"))
                .value(distribution.getDistributionDomainName())
                .build());

        new CfnOutput(this, "CloudFrontDistributionId", CfnOutputProps.builder()
                .exportName(applicationEnvironment.prefix("frontend-cloudfront-id"))
                .value(distribution.getDistributionId())
                .build());

        applicationEnvironment.tag(this);
    }

    private static String createParameterName(DeploymentStage stage, String key) {
        return stage.getName() + "-frontend-" + key;
    }

    private void putParameter(String constructId, DeploymentStage stage, String name, String value) {
        StringParameter.Builder.create(this, constructId)
                .parameterName(createParameterName(stage, name))
                .stringValue(value)
                .build();
    }
}